# TODO optimize ordering of Dockerfile commands
# Especially pertaining to playwright

FROM python:3.11

ARG USERNAME=ubuntu
ARG USER_UID=1000
ARG USER_GID=1000

WORKDIR /code

RUN pip install torch==2.6.0 --index-url https://download.pytorch.org/whl/cpu

COPY ./pyproject.toml .
RUN pip install --no-cache-dir --upgrade .

{% if USE_CHATBOT == "true" %}
# Install playwright browser dependencies under root user
RUN python -m playwright install-deps
{% endif %}

RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    && chown -R ${USER_UID}:${USER_GID} /code

USER $USERNAME

{% if USE_CHATBOT == "true" %}
# Install playwright browser under non-root user
RUN python -m playwright install
{% endif %}

COPY ./app /code/app
COPY ./scripts /code/scripts

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]
