FROM python:3.11

WORKDIR /code

COPY ./pyproject_temp.toml ./pyproject.toml
RUN pip install --no-cache-dir --upgrade .

COPY ./app_temp /code/app_temp


CMD ["uvicorn", "app_temp.main:app", "--host", "0.0.0.0", "--port", "80"]
