FROM python:3.11

ARG USERNAME=ubuntu
ARG USER_UID=1000
ARG USER_GID=1000

WORKDIR /code

RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME

RUN pip install --no-cache-dir --upgrade jinja2==3.1.6

USER $USERNAME
