{% if USE_GPU == "true" %}
FROM pytorch/pytorch:2.6.0-cuda12.4-cudnn9-runtime
{% else %}
FROM python:3.11
{% endif %}

ARG USERNAME=ubuntu
ARG USER_UID=1000
ARG USER_GID=1000

WORKDIR /code

{% if USE_GPU == "false" %}
RUN pip install torch==2.6.0 --index-url https://download.pytorch.org/whl/cpu

{% endif %}
COPY ./pyproject.toml .
RUN pip install --no-cache-dir --upgrade .

COPY ./app /code/app
COPY ./scripts /code/scripts

RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    && chown -R ${USER_UID}:${USER_GID} /code

USER $USERNAME

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]
