apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80        # Exposed port
      targetPort: 80  # Port on the container
  type: ClusterIP     # Change to LoadBa
