# TODO secrets from .env

apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  MILVUS__USER: your-milvus-user
  MILVUS__PASS: your-milvus-pass
  MILVUS_NEW_ROOT_PASS: your-new-root-pass
