{% if USE_GPU == "true" %}
FROM pytorch/pytorch:2.6.0-cuda12.4-cudnn9-runtime
{% else %}
FROM python:3.11
{% endif %}

ARG USERNAME=ubuntu
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Create a non-root user that has sudo privileges
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    && apt-get update \
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

USER $USERNAME

WORKDIR /code

{% if USE_GPU == "false" %}
RUN pip install torch==2.6.0 --index-url https://download.pytorch.org/whl/cpu

{% endif %}
# We cannot access files in parent directory .. (outside of defined context)
# TODO Once we reorganize the repo, we can change it to the way it was before
COPY ./pyproject.toml .
RUN pip install --no-cache-dir --upgrade .

COPY ./api/app /code/app
COPY ./api/data /code/data
COPY ./api/scripts/milvus_credentials_setup.py /code/scripts

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]
