services:
  # FastAPI service with GPU support
  app:
    build:
      context: .. #TODO change context once the repo is reorganized (we need pyproject.toml to be in the same folder as the dockerfiles)
      dockerfile: api/Dockerfile.gpu
    environment:
      - USE_GPU=true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
