services:
  app:
    environment:
      - MILVUS__EXTRACT_METADATA=true
      - OLLAMA__URI=http://ollama:11434
    depends_on:
      - ollama
  ollama:
    image: ollama/ollama:0.5.4
    volumes:
      - ${DATA_DIRPATH}/ollama:/root/.ollama/
    ports:
      - "${OLLAMA_HOST_PORT}:11434"
