services:
  # FastAPI service with GPU support
  app:
    build: 
      context: .
      dockerfile: Dockerfile.gpu
    environment:
      - USE_GPU=false
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
