FROM python:3.11

WORKDIR /code

COPY ./requirements-populate.txt .

RUN pip install --no-cache-dir --upgrade -r requirements-populate.txt

COPY ./scripts /code

CMD ["/bin/sh", "-c", "python populate_milvus.py --i $INPUT_DIRPATH --uri $MILVUS_URI"]
