services:
  # Python script for populating vector DB
  populate-db:
    build:
      context: .
      dockerfile: Dockerfile.populate
    environment:
      - INPUT_DIRPATH=/data_to_populate
      - MILVUS_URI=http://milvus-standalone:19530
    depends_on:
      - milvus-standalone
    volumes:
      - ${INITIAL_EMBEDDINGS_TO_POPULATE_DB_WITH_DIRPATH}:/data_to_populate
