services:
  app:
    environment:
      - MILVUS__EXTRACT_METADATA=true
      - OLLAMA__URI=http://ollama:11434
    depends_on:
      ollama:
        condition: service_healthy
        restart: false
  ollama:
    image: ollama/ollama:0.5.4
    labels: 
      autoheal-label: true
    restart: always
    healthcheck:
      test: ["CMD", "ollama"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - ${DATA_DIRPATH}/ollama:/root/.ollama/
    ports:
      - "${OLLAMA_HOST_PORT}:11434"
